#!/bin/sh
# QuikGIF MCP shim (version: 3)
# Generated by `quikgif mcp-install`. Safe to delete and re-create.
#
# If `quikgif` is on this machine, exec it as the MCP server.
# If not, serve a minimal MCP responder that explains how to install it.

# Hardening: error on unset vars. We deliberately avoid `set -e` because
# several conditionals below rely on non-zero exits as control flow, but
# every critical write/exec has its own explicit failure check below.
set -u

# Lookup order matches the curl install script: /usr/local/bin (sudo path),
# then ~/.local/bin (no-sudo fallback). Homebrew is checked LAST because the
# tap was deprecated 2026-04-16 and pinned at v1.4.0; we don't want a stale
# Cellar binary shadowing a current curl install (see PR #220 review).
for path in /usr/local/bin/quikgif "$HOME/.local/bin/quikgif" /opt/homebrew/bin/quikgif; do
    if [ -x "$path" ]; then
        exec "$path" mcp-server "$@"
    fi
done

# Fallback: try `which` (covers non-standard PATH installs).
cli="$(command -v quikgif 2>/dev/null || true)"
if [ -n "$cli" ] && [ -x "$cli" ]; then
    exec "$cli" mcp-server "$@"
fi

# No CLI found — run the embedded install-help stub. Requires python3
# (shipped with macOS via Xcode CLT). If python3 is also missing, fall
# back to a stderr-only message so the MCP host at least sees a clear
# explanation in its connection log.
if ! command -v /usr/bin/python3 >/dev/null 2>&1 && ! command -v python3 >/dev/null 2>&1; then
    echo "[QuikGIF MCP shim] quikgif CLI not found and python3 is unavailable." 1>&2
    echo "[QuikGIF MCP shim] Install QuikGIF: curl -fsSL https://quikgif.com/install.sh | sh" 1>&2
    exit 127
fi

PY="$(command -v /usr/bin/python3 || command -v python3)"
echo "[QuikGIF MCP shim] quikgif CLI not found — serving install-help stub." 1>&2

# The Python script lives in a temp file so we can `exec` it cleanly.
# If we used a heredoc here the heredoc itself would consume stdin and
# the JSON-RPC loop would have nothing to read from the MCP host.
#
# NOTE on cleanup: `exec` REPLACES this shell, so any sh-level `trap` would
# never fire. We rely on Python's own `os.unlink(__file__)` (below) to
# clean up the stub, with a stale-file sweep on entry as a backstop.
STUB_DIR="${TMPDIR:-/tmp}"
STUB="$STUB_DIR/quikgif-mcp-stub-$$.py"
if cat > "$STUB" <<'PYEOF'
import json
import os
import sys

# Self-clean: remove this temp file as soon as we're loaded. The shell
# parent has already `exec`'d into us, so no trap will fire to do this
# otherwise. Best-effort — never crash the responder over cleanup.
try:
    os.unlink(__file__)
except OSError:
    pass

INSTALL_TEXT = (
    "QuikGIF CLI is not installed on this machine.\n\n"
    "The QuikGIF MCP server (registered in your AI tool's config) cannot run\n"
    "because the underlying `quikgif` binary is missing.\n\n"
    "Install QuikGIF (one of):\n"
    "  1. CLI only: curl -fsSL https://quikgif.com/install.sh | sh\n"
    "  2. Mac app:  download from https://quikgif.com (or search\n"
    "     \"QuikGIF\" in the Mac App Store).\n\n"
    "After installing, restart your AI tool so it relaunches the MCP server.\n\n"
    "If you no longer want the QuikGIF MCP, run\n"
    "  quikgif mcp-uninstall\n"
    "or remove the `quikgif` entry from your MCP host's config (e.g.\n"
    "~/.claude.json under mcpServers)."
)

TOOLS = [
    {
        "name": "quikgif_install_help",
        "description": (
            "QuikGIF MCP fallback: the `quikgif` CLI is not installed on this "
            "machine. Call this tool for install instructions and links."
        ),
        "inputSchema": {"type": "object", "properties": {}},
    }
]

def respond(req_id, result=None, error=None):
    msg = {"jsonrpc": "2.0", "id": req_id}
    if error is not None:
        msg["error"] = error
    else:
        msg["result"] = result
    sys.stdout.write(json.dumps(msg) + "\n")
    sys.stdout.flush()

for raw in sys.stdin:
    line = raw.strip()
    if not line:
        continue
    try:
        req = json.loads(line)
    except Exception:
        continue
    method = req.get("method", "")
    rid = req.get("id")
    if method == "initialize":
        respond(rid, {
            "protocolVersion": "2024-11-05",
            "capabilities": {"tools": {}},
            "serverInfo": {
                "name": "quikgif (install help)",
                "version": "0.0.0",
            },
        })
    elif method == "notifications/initialized":
        # No response needed.
        continue
    elif method == "tools/list":
        respond(rid, {"tools": TOOLS})
    elif method == "tools/call":
        respond(rid, {
            "content": [{"type": "text", "text": INSTALL_TEXT}],
            "isError": True,
        })
    elif method == "ping":
        respond(rid, {})
    else:
        respond(rid, error={"code": -32601, "message": f"Method not found: {method}"})
PYEOF
then
    :
else
    echo "[QuikGIF MCP shim] Failed to write install-help stub to $STUB" 1>&2
    echo "[QuikGIF MCP shim] Install QuikGIF: curl -fsSL https://quikgif.com/install.sh | sh" 1>&2
    exit 1
fi

# Sweep any stale stub files this user has accumulated (>1 day old). The
# Python script unlinks itself on entry, so this is just defense in depth
# in case a previous run was SIGKILL'd before reaching that line.
find "$STUB_DIR" -maxdepth 1 -name 'quikgif-mcp-stub-*.py' -mtime +1 -delete 2>/dev/null || true

# Hand off: stdin/stdout/stderr stay attached to the MCP host.
exec "$PY" "$STUB"